### ISSUE TITLE
Customization commands not executing

### ISSUE THREAD

**Issue by BogdanMakarchuk** [Ad5001/HideAndSeek#1]
What kernel should I use? On of pmmp a lot of mistakes. And do, please, not the database (db), like this: /arena/arenaName.yml file, that is config

**Comment by Ad5001** [comment]
I prefer using databases because it's more organized. And many people got confused with configs on my last minigame plugin (UHC). You can use commands to modify the arena properties or using an SQLite3 editor (there are a lot free on the internet).
And about the errors, could you tell me them so I can fix them (having some trouble with testing since I need two players ;) to test the whole match)

**Comment by BogdanMakarchuk** [comment]
1. When you enter /ssp hideandseek [...] if I wrote "/hideandseek .....". The command I submit is correct , but they don't work.. can't customize the arena.. the only Working team /hideandseek addgame

**Comment by Ad5001** [comment]
Ok. Is there any error in the console?

**Comment by BogdanMakarchuk** [comment]
SELECT waiting_time FROM Games WHERE name = 'Mineplex - BlockHunt Map2 By MMD';;SELECT seekers_percentage FROM Games WHERE name = 'Mineplex - BlockHunt Map2 By MMD';;SELECT spawnpoint FROM Games WHERE name = 'Mineplex - BlockHunt Map2 By MMD';;
Notice: Undefined offset: 1 in /root/pvp/plugins/HideAndSeek-master/src/Ad5001/HideAndSeek/Game.php on line 217

**Comment by BogdanMakarchuk** [comment]
When you create the arena (/h&s addgame) spam in the console: Hunt';;select max_players from games where name = 'hunt';;select max_players from games where name = 'hunt';;select max_players from games where name = 'hunt';;select max_players from games where name = 'hunt';;select max_players from games where name = 'hunt';;select max_players from games where name = 'hunt';;max_players select from games where name = 'hunt';;select max_players from games where name = 'hunt';;Select max_players from games where name = 'hunt';;select max_players games where name = 'hunt';;select max_players from games where name = 'hunt';;select max_players from games Where name =

**Comment by Ad5001** [comment]
Oh that yeah it's debug. Will be fixed in the next commit.
And about the notice, it's just that the spawnpoint hasn't been set.

**Comment by BogdanMakarchuk** [comment]
New update (2017.03.09), error:

05:35:41] [Server thread/CRITICAL]: Error: "Call to undefined method Ad5001\HideAndSeek\DataBase::getLogger()" (EXCEPTION) in "/plugins/HideAndSeek-master/src/Ad5001/HideAndSeek/DataBase" at line 90

**Comment by Ad5001** [comment]
Oh yeah my bad. Will fix it.

**Comment by BogdanMakarchuk** [comment]
You have Twitte?

**Comment by BogdanMakarchuk** [comment]
/h&s addgame :
[07:45:11] [Server thread/INFO]: Подготовка мира "Hunt"

Warning: SQLite3Result::fetchArray(): Unable to execute statement: UNIQUE constraint failed: Games.Id in /root/pvp/plugins/HideAndSeek-master/src/Ad5001/HideAndSeek/DataBase.php on line 102
[07:45:49] [Server thread/NOTICE]: [HideAndSeek] Succefully registered game level Hunt.

**Comment by BogdanMakarchuk** [comment]
Here I enter the command: https://drive.google.com/file/d/0BwvXkkCZMP-7OVFHYkdjTkIwZ0E/view?usp=drivesdk

So when you enter all commands, only the messages are different: https://drive.google.com/file/d/0BwvXkkCZMP-7M05uWW1uelNDNVE/view?usp=drivesdk

**Comment by BogdanMakarchuk** [comment]
I think the problem is in the db

**Comment by Ad5001** [comment]
You can contact mpe on Twitter at @Ad5001P4F.
Also this bug should not affect anything

**Comment by Ad5001** [comment]
All commands are now been tested & fixed
