### ISSUE TITLE
how to join?

### ISSUE THREAD

**Issue by ghost** [Ad5001/HideAndSeek#4]
ok I've set everything but how do players enter the game? it didn't tell me to touch a sign or anything

**Comment by Ad5001** [comment]
They just have to join the world :)
You can use any WorldTP plugin with signs, create one and players wilol ba able to TP to it.
I was working on a sign system. But I abandoned it due to some software bugs.

**Comment by ghost** [comment]
ok dude i have a bedwars plugin idk who made it but it only has one problem which is when players die in the game it doesn't teleport them back to thier teams spawn it just makes them stuck in the air . can u fix it ? should i upload the plugin for u?

**Comment by Ad5001** [comment]
Off topic. Contact me by mail at mail@ad5001.eu.
