### ISSUE TITLE
Error!!!

### ISSUE THREAD

**Issue by PluginBOXone** [Ad5001/HideAndSeek#5]
When i make /hideandseek addgame or help or stop ..... comes an error in the Console!  CRITICAL> The command 'hideandseek addgame' in hideandseek: Call to undefined method pocketmine\command\ConsoleCommandSender::getLevel()
[Tesseract] [17:17:45] CRITICAL> Error: "Call to undefined method pocketmine\command\ConsoleCommandSender::getLevel()" (EXCEPTION) in "/HideAndSeek-master/src/Ad5001/HideAndSeek/Main" at line 77

**Comment by Ad5001** [comment]
Use these commands in game. I need to add a warning about this.
Please note that all the commands are level relative which means it executes on the level you're on.

**Comment by PluginBOXone** [comment]
oh thank you!
